# Generated by Django 4.1.7 on 2023-03-30 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='featured_image',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
