# Generated by Django 4.1.7 on 2023-03-31 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_service_featured_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Service',
            new_name='Workshop',
        ),
    ]
