# Generated by Django 4.1.7 on 2023-03-31 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermsPrivacySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sec_type', models.CharField(choices=[('terms', 'Terms'), ('privacy', 'Privacy')], max_length=20)),
                ('heading', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
