# Generated by Django 4.1.7 on 2023-03-31 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_termsprivacysection'),
    ]

    operations = [
        migrations.AddField(
            model_name='termsprivacysection',
            name='s_order',
            field=models.IntegerField(default=0),
        ),
    ]
